name: 'Setup ChromeDriver'
description: 'Setup ChromeDriver via WebDriverManager'
runs:
  using: "composite"
  steps:
    - run: |
        wget https://github.com/bonigarcia/webdrivermanager/releases/download/webdrivermanager-5.1.0/webdrivermanager-5.1.0-fat.jar
        java -jar webdrivermanager-5.1.0-fat.jar resolveDriverFor chrome
        chromedriver --version
      shell: bash
