name: 'browsers'
on:
  pull_request:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

jobs:
  build:
    strategy:
      matrix:
        browser: [chromium, firefox, edge]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: browser-actions/setup-firefox@v1
        if: matrix.browser == 'firefox'
        with:
          firefox-version: "latest"
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: "stable"
        if: matrix.browser == 'chromium'
      - uses: browser-actions/setup-edge@v1
        if: matrix.browser == 'edge'
        with:
          edge-version: "stable"

  
