name: 'browsers'
on:
  workflow_dispatch:  

jobs:
  windows:
    strategy:
      matrix:
        browser: [chrome, edge]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhi1693/setup-browser@v0.3.4
        name: Chrome Latest
        with:
          browser: chrome
          version: latest      
      - uses: browser-actions/setup-chrome@v1
        name: Chrome Stable
        with:
          chrome-version: "stable"
        if: matrix.browser == 'chrome'
      - uses: browser-actions/setup-edge@v1
        name: Edge Stable
        if: matrix.browser == 'edge'
        with:
          edge-version: "stable"
      - uses: browser-actions/setup-chrome@v1
        name: Chrome Beta
        with:
          chrome-version: "beta"
        if: matrix.browser == 'chrome'
      - uses: browser-actions/setup-edge@v1
        name: Edge Beta
        if: matrix.browser == 'edge'
        with:
          edge-version: "beta"

  ubuntu:
    strategy:
      matrix:
        browser: [chrome, edge]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhi1693/setup-browser@v0.3.4
        name: Chrome Latest
        with:
          browser: chrome
          version: latest      
      - uses: browser-actions/setup-chrome@v1
        name: Chrome Stable      
        with:
          chrome-version: "stable"
        if: matrix.browser == 'chrome'
      - uses: browser-actions/setup-edge@v1
        name: Edge Stable      
        if: matrix.browser == 'edge'
        with:
          edge-version: "stable"
      - uses: browser-actions/setup-chrome@v1
        name: Chrome Beta
        with:
          chrome-version: "beta"
        if: matrix.browser == 'chrome'
      - uses: browser-actions/setup-edge@v1
        name: Edge Beta
        if: matrix.browser == 'edge'
        with:
          edge-version: "beta"

  macos:
    strategy:
      matrix:
        browser: [chrome, edge]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhi1693/setup-browser@v0.3.4
        name: Chrome Latest
        with:
          browser: chrome
          version: latest      
      - uses: browser-actions/setup-chrome@v1
        name: Chrome Stable      
        with:
          chrome-version: "stable"
        if: matrix.browser == 'chrome'
      - uses: browser-actions/setup-edge@v1
        name: Edge Stable      
        if: matrix.browser == 'edge'
        with:
          edge-version: "stable"
      - uses: browser-actions/setup-chrome@v1
        name: Chrome Beta
        with:
          chrome-version: "beta"
        if: matrix.browser == 'chrome'
      - uses: browser-actions/setup-edge@v1
        name: Edge Beta
        if: matrix.browser == 'edge'
        with:
          edge-version: "beta"
  
